CREATE DATABASE IF NOT EXISTS BANKAYA;
USE BANKAYA;
CREATE TABLE IF NOT EXISTS CUSTOMER(
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    phone_number VARCHAR(30),
    curp VARCHAR(30),
    rfc VARCHAR (30) NOT NULL,
    address_cust TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS ITEMS(
    id INT PRIMARY KEY AUTO_INCREMENT,
    item VARCHAR(30) NOT NULL,
    price decimal NOT NULL
);
CREATE TABLE IF NOT EXISTS ITEMS_BOUGHT(
    order_number INT PRIMARY KEY AUTO_INCREMENT,
    date_order date NOT NULL,
    price decimal NOT NULL,
    id_items INT,
    id_customers INT,
    FOREIGN KEY (id_items) REFERENCES ITEMS(id) ON DELETE SET NULL,
    FOREIGN KEY (id_customers) REFERENCES CUSTOMER(id) ON DELETE SET NULL
);